"""
Speaking Postgres while the code keeps writing SQLite.

The application holds roughly two hundred hand-written SQL statements, and
`get_db` is the single place they all get a connection from. That chokepoint is
the whole reason this port is a module rather than a rewrite of forty-seven
files: everything above it can keep passing `?` placeholders and reading rows
by name, and this layer makes that mean the right thing to asyncpg.

The one genuinely dangerous piece is placeholder translation, so it is worth
being explicit about why it is safe. Turning `?` into `$1, $2, ...` is
positional and carries no meaning -- it does not parse, rewrite or reorder
anything. The only way it can go wrong is by rewriting a question mark that
was never a placeholder, which means one inside a string literal, so that is
the case the scanner exists to handle and the case most of the tests are
about.

What this deliberately does NOT do is translate SQL dialect. A layer that
quietly rewrites date functions and upserts is a small ORM with none of an
ORM's testing, and its failure mode is a query that is *almost* right --
silently wrong data in an application whose entire job is telling people the
truth about their money. Dialect differences are fixed at the source instead,
in portable SQL that both engines read the same way.
"""
from __future__ import annotations


def translate(sql: str) -> str:
    """
    Rewrite `?` placeholders as `$1`, `$2`, ... leaving everything else alone.

    Question marks inside quoted strings are left untouched. SQL uses doubled
    quotes to escape a quote inside a literal (`'it''s'`), which needs no
    special handling here: the closing quote ends the literal and the next one
    immediately opens another, so the scanner stays outside the literal for
    exactly zero characters and any `?` in between is still correctly seen as
    quoted.
    """
    return _scan(sql)[0]


def placeholder_count(sql: str) -> int:
    """
    How many parameters a statement expects.

    Worth having separately so that a mismatch between the SQL and the tuple
    passed to it is reported as that, rather than as an asyncpg error about a
    parameter number that nothing in the source code contains.
    """
    return _scan(sql)[1]


def _scan(sql: str) -> tuple[str, int]:
    out: list[str] = []
    index = 0
    quote: str | None = None

    for char in sql:
        if quote:
            # Inside a literal or a quoted identifier: copy verbatim.
            if char == quote:
                quote = None
            out.append(char)
            continue

        if char in ("'", '"'):
            quote = char
            out.append(char)
            continue

        if char == "?":
            index += 1
            out.append(f"${index}")
            continue

        out.append(char)

    return "".join(out), index


# ─────────────────────────────────────────────────────────────────────────────
# Schema translation
#
# Unlike query translation, rewriting CREATE TABLE is safe to do mechanically,
# and the distinction is worth stating because it looks like the same thing.
# DDL runs once at startup and cannot be subtly wrong: a type that translates
# badly either fails immediately or produces a column that every later query
# visibly rejects. There is no version of this that quietly stores the wrong
# number. Queries are the opposite, which is why they are left alone.

_TYPES = [
    # The primary key first, because it is the only genuine difference: SQLite
    # gives every INTEGER PRIMARY KEY an implicit rowid, Postgres needs to be
    # told to generate one.
    ("INTEGER PRIMARY KEY AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
    ("INTEGER PRIMARY KEY", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
    # Postgres has no unsized INTEGER-as-anything; BIGINT is what the ids and
    # counters actually need, and REAL is a 4-byte float there, which is far
    # too little for money.
    ("REAL", "DOUBLE PRECISION"),
    ("INTEGER", "BIGINT"),
]


def translate_schema(ddl: str) -> str:
    """Rewrite a SQLite CREATE TABLE statement for Postgres."""
    out = ddl
    for sqlite_type, postgres_type in _TYPES:
        out = out.replace(sqlite_type, postgres_type)
    return out


class _Execution:
    """
    The result of `execute`, which has to be two things at once.

    The application uses both spellings, sometimes in adjacent lines:

        cursor = await db.execute(...)
        async with db.execute(...) as cursor:

    aiosqlite supports both because its result object is awaitable *and* an
    async context manager. A plain coroutine is only the first, so the second
    form raises TypeError -- at runtime, in whichever route happened to use
    it, not at import. Roughly half the read paths in this codebase are
    written the second way, so a wrapper that only supported `await` would
    look correct in isolation and take down most of the application.

    The work is deferred until whichever form is used, and cached, so neither
    spelling runs the statement twice.
    """

    def __init__(self, run):
        self._run = run
        self._cursor: Cursor | None = None

    async def _resolve(self) -> "Cursor":
        if self._cursor is None:
            self._cursor = await self._run()
        return self._cursor

    def __await__(self):
        return self._resolve().__await__()

    async def __aenter__(self) -> "Cursor":
        return await self._resolve()

    async def __aexit__(self, *exc) -> bool:
        return False


class Cursor:
    """
    The small part of a DB-API cursor this codebase actually uses.

    Deliberately holds already-fetched rows rather than streaming. Every query
    in the application is a bounded lookup or an explicitly LIMITed list, and
    a real cursor would mean holding a connection open across the `async with`
    blocks that are written all over the routers.
    """

    def __init__(self, rows: list, rowcount: int = -1):
        self._rows = rows
        self.rowcount = rowcount

    async def fetchone(self):
        return self._rows[0] if self._rows else None

    async def fetchall(self):
        return self._rows

    async def __aenter__(self):
        return self

    async def __aexit__(self, *exc):
        return False


class Connection:
    """
    An aiosqlite-shaped connection over asyncpg.

    `row_factory` is accepted and ignored: asyncpg's Record already supports
    both `row["name"]` and `row[0]`, which is the entire reason the calling
    code needs no changes.

    `commit` is a no-op because asyncpg autocommits each statement and nothing
    in this codebase rolls back -- verified, not assumed. If a transaction is
    ever genuinely needed, it must be an explicit `async with conn.transaction()`
    rather than a quiet change of meaning here.
    """

    row_factory = None

    def __init__(self, conn):
        self._conn = conn

    def execute(self, sql: str, params=()) -> _Execution:
        # Deliberately not `async def`: the caller may `await` this or use it
        # as an async context manager, and only a returned object can be both.
        return _Execution(lambda: self._execute(sql, params))

    async def _execute(self, sql: str, params=()) -> Cursor:
        statement = translate(sql)
        args = tuple(params or ())

        expected = placeholder_count(sql)
        if expected != len(args):
            # Reported here rather than by the driver, which would name a
            # parameter number that appears nowhere in the source.
            raise ValueError(
                f"SQL expects {expected} parameter(s) but {len(args)} were given: {sql!r}"
            )

        if statement.lstrip()[:6].upper() == "SELECT" or " RETURNING " in statement.upper():
            # asyncpg has no `lastrowid`, so the five inserts that used to want
            # one now say RETURNING id and are read like any other query. That
            # is portable SQL rather than a driver feature, which is why the
            # cursor here deliberately does not pretend to offer lastrowid.
            rows = await self._conn.fetch(statement, *args)
            return Cursor(list(rows), len(rows))

        status = await self._conn.execute(statement, *args)
        return Cursor([], _affected(status))

    async def executemany(self, sql: str, seq) -> Cursor:
        await self._conn.executemany(translate(sql), [tuple(row) for row in seq])
        return Cursor([])

    async def commit(self) -> None:
        return None

    async def close(self) -> None:
        await self._conn.close()


def _affected(status: str) -> int:
    """
    Row count out of an asyncpg status tag such as "UPDATE 3".

    Returns -1 when the tag carries no count, which is what DB-API uses for
    "unknown" -- reporting 0 would be a claim that nothing changed.
    """
    parts = (status or "").split()
    return int(parts[-1]) if parts and parts[-1].isdigit() else -1
