export const PRODUCTS = [
  { key: 'cost', slug: 'azure-cost-intelligence', label: 'Cost intelligence', title: 'From cloud spend to a clear explanation.', description: 'Explore Azure cost trends, daily changes, reservation charges and BOQ variance with resource-level billing context.', audience: 'For FinOps and finance teams', outcome: 'Explain the bill', steps: ['Scope the reporting period', 'Compare the biggest changes', 'Trace the resource and meter'], context: 'Use a consistent currency, subscription selection and cost basis. Partial responses and recent billing data can change totals; check freshness before making a financial decision.', details: {
    explorer: 'Move between trends, daily timelines, month comparison, bandwidth and resource groups. Start with a service-level change, then inspect resource and meter contributions to separate usage growth from billing events.',
    commitments: 'Review reservation and savings-plan utilization, coverage and upcoming expiry where Azure provides the data. Inspect amortized allocation and purchase context before interpreting a billing spike or considering another commitment.',
    boq: 'Compare a Pricing Calculator estimate with billed costs. Inspect matched lines, unbudgeted services and missing matches, then drill into the resources behind the variance. An estimate remains a baseline, not a guaranteed invoice.',
    deploy: 'Describe an infrastructure requirement or upload a BOQ to draft a plan and review pricing assumptions. Generated templates can be reviewed separately; creating resources through Build is an explicit, permission-checked action.',
  } },
  { key: 'estate', slug: 'azure-resource-optimization', label: 'Resource intelligence', title: 'Connect what is running with what it costs.', description: 'Investigate Azure resource changes, utilization and orphaned-resource candidates in a connected operational review.', audience: 'For cloud operations and platform teams', outcome: 'Prioritize the right changes', steps: ['Review the estate', 'Check utilization and changes', 'Validate with the workload owner'], context: 'Low utilization or a missing attachment is a review signal, not an automatic deletion instruction. Include peak demand, recovery requirements and dependencies before changing a workload.', details: {
    anomalies: 'Identify unusual cost changes and inspect their billing context. An anomaly highlights where to investigate; correlation with an activity event does not by itself establish causation.',
    changes: 'Compare resource snapshots to find additions, removals and configuration changes. Match the affected resource IDs with the cost timeline to investigate what changed during the reporting period.',
    activity: 'Read Azure Activity Log events to see operations, timestamps and actors when available. Azure retention and your selected scope determine the available history.',
    compute: 'Review VM utilization and sizing signals over the available observation window. CPU, memory availability, workload peaks and disk or network constraints should all inform a rightsizing decision.',
    orphaned: 'Find unattached disks, IP addresses and network-interface candidates. Inspect ownership, dependencies and observed costs before retirement; not every resource candidate has a direct recurring charge.',
    provision: 'Draft supported VMs, storage accounts, virtual networks and web apps from a form. Deployment requires workspace-admin authorization, explicit confirmation and sufficient Azure permissions. Resource creation incurs Azure charges.',
  } },
  { key: 'security', slug: 'azure-access-governance', label: 'Access and governance', title: 'See exposure alongside your cloud estate.', description: 'Review Azure access, Defender findings, policy compliance, Advisor recommendations and network relationships in one workspace.', audience: 'For security and governance teams', outcome: 'Understand the exposure', steps: ['Inspect access and findings', 'Review the affected scope', 'Assign an evidence-led follow-up'], context: 'These views surface Azure data and review signals. A secure score is not a compliance certification, and incomplete directory access can leave identities visible only as IDs.', details: {
    'access-identity': 'Explore role assignments and what an identity can reach. Review potentially unused, stale or overlapping grants with their scope and available evidence rather than treating a flag as proof that access is unnecessary.',
    advisor: 'Bring Azure Advisor recommendations into the same review as cost and inventory. Check the recommendation’s scope, assumptions and date before estimating the impact of an action.',
    defender: 'Review Defender findings and secure score while keeping alerts distinct from configuration recommendations. Coverage depends on the connected subscription, permissions and enabled Azure services.',
    policy: 'Inspect compliance, assignments and exemption expiry across scans. Use the underlying policy context to distinguish an expected exemption from an item needing remediation.',
    network: 'Explore virtual networks, peerings, gateways and subnet relationships, including attached security groups and route tables. A topology view explains configuration; it is not a live packet trace.',
  } },
  { key: 'account', slug: 'azure-team-workspace', label: 'Connected workspace', title: 'One workspace. Clear context for every review.', description: 'Connect Azure tenants, manage team access and understand the data sources behind Cloudledger reports.', audience: 'For workspace owners and team leads', outcome: 'Keep the team in context', steps: ['Connect your tenant', 'Choose subscriptions and roles', 'Review sources and freshness'], context: 'Reporting uses the connected Azure permissions. Some data sources need additional roles or directory consent. Refresh an expired tenant session in Settings to restore access.', details: {
    settings: 'Manage tenant connections, reporting scope and supported imports. Select the relevant subscriptions and dates, and check connection status when a report is incomplete or a session expires.',
    team: 'Invite directory colleagues and assign workspace roles. Server-side role checks complement the interface; an app role does not bypass the permissions required by Azure.',
    apis: 'Explore the Microsoft endpoints behind the application, including public retail-pricing sources. Use source context to distinguish billed cost, retail estimates, resource inventory and recommendations.',
  } },
];
export const productPath = (product) => `/features/${product.slug}/`;
